# numpy
- 수치 연산에 최적화된 Python 라이브러리임
- 다차원 배열 연산 처리 가능함
- 선형대수 등 다양한 수학 연산 지원함
- Python list 대비 시간/공간 효율이 좋음


## 환경설정
- NumPy 설치 및 버전 확인용 섹션임


In [ ]:
## 환경설정
# NumPy 설치 및 버전 확인용 섹션임
!pip install numpy


In [ ]:
# Numpy import 및 설치확인
import numpy as np

np, np.__version__


## ndarray(엔디어레이)
- N-dimensional array의 약자임
- 다차원 데이터를 저장하고 연산하는 NumPy 배열 타입임
- 같은 배열 안의 원소는 하나의 `dtype`을 가짐


In [ ]:
# ndarray 생성
a = np.array([1, 2, 3])  # 1차원 ndarray생성
print(type(a))
print(a)

b = np.array([4, 5, 6, ])

# ndarray 연산
c = a + b
print("a : ", a)
print("b : ", b)
print("c : ", c)

print("a.shape", a.shape)  # (3,) = 1차원의 요사가 3개가있다
print("a.size", a.size)  # 3 = ndarray의 전체 요소 개수



### 실습
- 과일 판매량 데이터 사용함
- NumPy 배열로 분기별 판매량 계산함
- 구할 값: 과일별 총 판매량, 과일별 평균 판매량임

- **데이터**
  - 1분기 판매량: `[200, 340, 150, 400]`
  - 2분기 판매량: `[220, 300, 180, 420]`
  - 과일 순서: 사과, 배, 오렌지, 바나나임


In [ ]:
fruits = ['사과', '배', '오랜지', '바나나']

sales_q1 = [200, 340, 150, 400]
sales_q2 = [220, 300, 180, 420]

# 총 판매량
total_sales = np.array(sales_q1) + np.array(sales_q2)

print("과일명 : ", fruits)
print("과일별 총 판매량 : ", total_sales)
# # 과일별 총 판매량
# for i, t in enumerate(total):
#     print(f'{fruits[i]} 총 판매량 : {t}')

# 과일별 평균 판매량
avg_totlal = total_sales / 2
print("과일별 평균 판매량 : ", avg_totlal)


### ndarray 속성
- `shape`: 배열의 모양임
- `ndim`: 배열의 차원 수임
- `size`: 전체 원소 개수임
- `dtype`: 배열 원소의 데이터 타입임

#### dtype
- 배열 요소의 데이터 타입임
- ndarray는 한 배열 안에 하나의 dtype을 가짐

| 범주 | 종류 | 요약 |
|:---|:---|:---|
| 정수형 | `int8`, `int16`, `int32`, `int64` | 부호 있는 정수 타입임 |
| 정수형(부호 없음) | `uint8`, `uint16`, `uint32`, `uint64` | 음수 없는 정수 타입임 |
| 부동소수형 | `float16`, `float32`, `float64` | 실수 표현 타입임 |
| 복소수형 | `complex64`, `complex128` | 실수부와 허수부를 가지는 타입임 |
| 불리언형 | `bool_` | `True` 또는 `False` 표현 타입임 |
| 문자열형 | `string_`, `bytes_` | 고정 길이 문자열 타입임 |
| 유니코드형 | `unicode_` | 다국어 문자 표현 타입임 |
| 객체형 | `object_` | Python 객체 참조 저장 타입임 |
| 날짜/시간형 | `datetime64`, `timedelta64` | 날짜/시간 저장 타입임 |


In [ ]:
# 1차원
array = np.array([2, 3, 4])
print("array : ", array)
print("array.shape 몇행 몇열 : ", array.shape)  # 1차원의 요소 == 행렬개념
print("array.ndim  몇차원인지 : ", array.ndim)  # 차원의 개수
print("array.size 원소의 개수 : ", array.size)  # 전체 원소의 개수
print("array.dtype 원소의 타입: ", array.dtype)  # 저장된 타입의 요소

In [ ]:
# 2차원
arr2 = np.array([[1, 2, 3], [3, 5, 6]])
print("arr2 : \n", arr2)
print("arr2.shape 몇행 몇열 : ", arr2.shape)  # 1차원의 요소 == 행렬개념
print("arr2.ndim  몇차원인지 : ", arr2.ndim)  # 차원의 개수
print("arr2.size 원소의 개수 : ", arr2.size)  # 전체 원소의 개수
print("arr2.dtype 원소의 타입: ", arr2.dtype)  # 저장된 타입의 요소

In [ ]:
# 3차원
temp = (
    [
        [[1, 2, 3, ], [4, 5, 6, ]],
        [[7, 8, 9, ], [10, 11, 12]]
    ]
)
arr3 = np.array(temp)
print("arr3 : \n", arr3)
print("arr3[0,0,0] : \n", arr3[0, 0, 0])
print("arr3[0,0,0] : \n", arr3[1, 0, 0])
print("arr3.shape 몇행 몇열 : ", arr3.shape)  # 1차원의 요소 == 행렬개념
print("arr3.ndim  몇차원인지 : ", arr3.ndim)  # 차원의 개수
print("arr3.size 원소의 개수 : ", arr3.size)  # 전체 원소의 개수
print("arr3.dtype 원소의 타입: ", arr3.dtype)  # 저장된 타입의 요소

### 특정 형식의 ndarray 생성
- `np.zeros(shape)`: 0으로 채워진 ndarray 생성함
- `np.ones(shape)`: 1로 채워진 ndarray 생성함
- `np.full(shape, n)`: 특정 값으로 채워진 ndarray 생성함
- `np.zeros_like(ndarray)`: 기존 배열과 같은 shape의 0 배열 생성함
- `np.ones_like(ndarray)`: 기존 배열과 같은 shape의 1 배열 생성함
- `np.full_like(ndarray, n)`: 기존 배열과 같은 shape의 특정 값 배열 생성함


In [ ]:
# 기본값 0으로 생성
arr1 = np.zeros((3, 2))
print(arr1)

arr2 = np.zeros((3, 2), dtype=int)
print(arr2)


In [ ]:
# np.once : 기본값 1로 배열 생성
arr3 = np.ones((3, 2, 3), dtype=int)
print(arr3)

In [ ]:
# np.full : 특정 값으로 지정해서 배열 생성
arr4 = np.full((4, 3, 2), 3.3)
print(arr4)

In [50]:

arr5 = np.array([[10, 20, 30], [40, 50, 60]])
print(np.zeros_like(arr5))

print(np.ones_like(arr5))

print(np.full_like(arr5, 7))

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[7 7 7]
 [7 7 7]]


### 특정 범위의 ndarray 생성
- `np.arange(start, stop, step)`: `start`부터 `stop` 전까지 `step` 간격으로 생성함
- `np.linspace(start, stop, num)`: `start`부터 `stop`까지 `num`개 균등 간격으로 생성함
- `np.logspace(start, stop, num, base)`: 지수 간격 값을 생성함


In [53]:
# np.arange() : 파이썬의 range()처럼 일정 간격 숫자 배열 생성
arr1 = np.arange(0, 10)
print('array 1 : ', arr1)

arr2 = np.arange(0, 10, 2)
print('array 2 : ', arr2)


array 1 :  [0 1 2 3 4 5 6 7 8 9]
array 2 :  [0 2 4 6 8]
array 1 :  [0 1 2 3 4 5 6 7 8 9]


In [55]:
# np.linspace() : start 부터 stop까지 num개로 쪼개기
arr3 = np.linspace(0, 10, 10)
print('array 3 : ', arr3)

arr4 = np.linspace(0, 10, 11)
print('array 3 : ', arr4)

array 3 :  [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
array 3 :  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [57]:
# np.logspace(start, stop, num, base) : start 부터 sop까지 num개의 숫자를 지수로 하는 base 거듭재곱
arr5 = np.logspace(1, 10, 10, base=2)
print('array 5 : ', arr5)

arr6 = np.logspace(1, 10, 10)
print('array 6 : ', arr6)

array 5 :  [   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
array 6 :  [1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [59]:
# ndarray는 하나의 타입(dtype)으로만 요소를 가질 수 있다
# 숫자와 문자가 혼용되면 NumPy가 자동으로 전체 원소를 저장할 수 있는
# 공통 타입으로 형변환을 시킨다
arr = np.array([1, 2, 3, '4'])
print(arr, ",", arr.dtype, ",", type(arr))


['1' '2' '3' '4'] <U21 <class 'numpy.ndarray'>


# ndarray 기초 실습 문제
1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열

In [64]:
# 1. 크기가 4x3인 모든 값이 0인 배열
arr1 = np.zeros((4, 3), dtype=int)
print("arr1 :\n", arr1)
# 2. 크기가 3x3인 모든 값이 1인 배열
arr2 = np.ones((3, 3), dtype=int)
print("arr2 : \n", arr2)
# 3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
arr3 = np.arange(0, 20, 5)
print("arr3 : ", arr3)
# 4. 0과 1 사이의 4개의 등간격 값을 가진 배열
arr4 = np.linspace(0, 1, 4)
print("arr4 : ", arr4)

arr1 :
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
arr2 : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
arr3 :  [ 0  5 10 15]
arr4 :  [0.         0.33333333 0.66666667 1.        ]
arr5 :  [ 1.          2.15443469  4.64158883 10.        ]
