# ndarray 연산
- NumPy 배열 간 연산 정리임
- 원소별 연산, broadcasting, 행렬곱, axis 연산 포함함


In [7]:
import numpy as np

## n차원 배열 연산
- 같은 shape끼리 원소별 연산 가능함
- 같은 위치의 값끼리 계산함
- 결과 shape도 기존 shape와 같음


In [8]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.full_like(arr1, 2)

# print(arr1)
# print(arr2)

# print(arr1 + arr2)
# print(arr1 - arr2)
# print(arr1 * arr2)
# print(arr1 / arr2)
# print(arr1 // arr2)
# print(arr1 % arr2)
# print(arr1 ** arr2)


## broadcasting 연산 방식
- shape가 다른 배열도 규칙이 맞으면 연산 가능함
- 작은 배열을 큰 배열 shape에 맞춰 해석함
- 실제 배열을 복사해서 키우는 것은 아님

**broadcasting 규칙**
- 뒤쪽 차원부터 비교함
- 두 차원이 같으면 가능함
- 둘 중 하나가 1이면 가능함
- 둘 다 다르고 1도 아니면 불가함

![](https://d.pr/i/D0XITM+)
![](https://d.pr/i/fka9ED+)


In [12]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.full((3,), 2)  # 1차원에 원소가 2 [2,2,2]

print(arr1)
print(arr2)

print("arr1 + arr2 : \n", arr1 + arr2)

[[1 2 3]
 [4 5 6]]
[[2 2 2]
 [2 2 2]]


In [20]:
arr = np.array([1, 2])
# print(arr.shape)

# print(arr1 + arr)
# (2,3) + (1,2)
# 행과 열중 하나라도 길이가 맞아야 가능
# - 제일 끝 차원인 3,2가 같지 않고, 둘중 1이 없음
# 브로드케스트 불가

In [22]:
# 스칼라 연산
# 스칼라? : 값이 1개 또는 길이(size)가 1인 배열과의연산
print("arr1:\n", arr1)
print("arr1 + 10:\n", arr1 + 10)
print("arr1 + [10]:\n", arr1 + [10])
print("arr1 + [[10]]:\n", arr1 + [[10]])
print("arr1 + [[[10]]]:\n", arr1 + [[[10]]])


arr1:
 [[1 2 3]
 [4 5 6]]
arr1 + 10:
 [[11 12 13]
 [14 15 16]]
arr1 + 10:
 [[11 12 13]
 [14 15 16]]


In [26]:
arr3 = np.array([[1], [2]])
print("arr3:\n", arr3)  # arr3.shape = (2,1)
print("arr1:\n", arr1)  # arr3.shape = (2,3)

# 2,3,4
# 6,7,8

print(arr1 + arr3)

arr3:
 [[1]
 [2]]
arr1:
 [[1 2 3]
 [4 5 6]]
[[2 3 4]
 [6 7 8]]


In [27]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])
arr3 = arr1 + arr2

# 2,2
print("arr1:\n", arr3.shape)
# [[6,7]
# [9,10]]
print("결과:\n", arr3)


arr1:
 (2, 2)
결과:
 [[ 6  7]
 [ 9 10]]


In [28]:
arr1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])  #shape = 3,3
arr2 = np.array([5, 6, 7])  # (,3)
# 5,6,7
# 6,7,8
# 7,8,9
arr3 = arr1 + arr2
print(arr3)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


## 행렬곱셈 Matrix Multiplication
- 점곱연산 Dot Product, 내적이라고도 함
- NumPy의 `*` 연산과 행렬곱은 다름
- `*`: 같은 위치 원소끼리 곱함
- `@`, `np.dot()`, `np.matmul()`: 행렬곱 수행함

**계산 방식**
- 왼쪽 행과 오른쪽 열을 짝지어 계산함
- 같은 위치끼리 곱한 뒤 모두 더함
- 결과의 한 칸은 왼쪽 행과 오른쪽 열의 내적값임

**shape 조건**
- 첫 번째 행렬의 열 수와 두 번째 행렬의 행 수가 같아야 함
- 행렬곱 shape: `(m, n) @ (n, p) -> (m, p)`
- 결과 shape: 바깥쪽 숫자인 `(m, p)`


- **수식**: 행렬 $ A $가 $ m \times n $ 크기이고, 행렬 $ B $가 $ n \times p $ 크기일 때, 행렬 곱 $ A \times B $의 결과는 $ m \times p $ 크기의 행렬이다. 곱셈 과정은 다음과 같다:
  $$
  (A \times B)_{ij} = \sum_{k=1}^{n} A_{ik} \times B_{kj}
  $$
  즉, $ A $의 i번째 행과 $ B $의 j번째 열에 해당하는 원소들을 곱하고, 그 결과를 더하여 새로운 행렬의 $ (i, j) $ 위치에 배치한다.

- **예시**:
  $$
  A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}, \quad B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}
  $$
  $$
  A \times B = \begin{pmatrix} 1 \cdot 5 + 2 \cdot 7 & 1 \cdot 6 + 2 \cdot 8 \\ 3 \cdot 5 + 4 \cdot 7 & 3 \cdot 6 + 4 \cdot 8 \end{pmatrix} = \begin{pmatrix} 19 & 22 \\ 43 & 50 \end{pmatrix}
  $$
- **예시2**
  결과 행렬의 각 원소는 **왼쪽 행렬의 행(Row)** 과 **오른쪽 행렬의 열(Column)** 을 곱한 뒤 더해서 계산한다.

    $$
    (A \times B)_{ij}
    =
    \sum_{k=1}^{n}
    A_{ik}B_{kj}
    $$

    즉,

    $$
    \begin{pmatrix}
    a & b \\
    c & d
    \end{pmatrix}
    \times
    \begin{pmatrix}
    e & f \\
    g & h
    \end{pmatrix}
    =
    \begin{pmatrix}
    ae+bg & af+bh \\
    ce+dg & cf+dh
    \end{pmatrix}
    $$

- **결과**: 새로운 **행렬**.

In [34]:
arr1 = [[1, 2],
        [3, 4]]

arr2 = [
    [5, 6],
    [7, 8]
]

a = np.array(arr1)
b = np.array(arr2)

print(a * b)

#내적 연산(행렬 곱)
print(np.multiply(a, b))
print(np.dot(a, b))
print('-' * 20)
print(a @ b)


[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
--------------------
[[19 22]
 [43 50]]


In [36]:
c = np.array(
    [
        [1, 2]  # 1,2
    ]
)
d = np.array(
    [
        [3],  # 2, 1
        [4]
    ]
)
# 1행2열과 2행1열의 곱이라
# 1행1열의 결과가 나옴
# 대신 차원은 높은치로 리턴됨
print("c@d:", c @ d)

[[11]]


In [37]:
# 2,3
e = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
# 3,2
f = np.array(
    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
)
# 2행3열과 3행2열이기때문에
# 더 작은값은 2행2열이 리턴됨
print(e @ f)

[[ 58  64]
 [139 154]]


## 기타연산
- 절대값, 반올림, 올림, 내림, 버림등이 연산

In [43]:
# 절대값
arr1 = np.array([[1, 2], [0, -1]])
print(np.abs(arr1))
arr2 = np.array([-1.234, 1.234, 2.345, 3.456, 4.567])
print("np.ceil(arr2):", np.ceil(arr2))
print("np.round(arr2):", np.round(arr2))

print("np.floor(arr2):", np.floor(arr2))
print("np.trunc(arr2):", np.trunc(arr2))


[[1 2]
 [0 1]]
np.ceil(arr2): [-1.  2.  3.  4.  5.]
np.round(arr2): [-1.  1.  2.  3.  5.]
np.floor(arr2): [-2.  1.  2.  3.  4.]
np.trunc(arr2): [-1.  1.  2.  3.  4.]


### axis 속성
- 연산을 처리할 축 지정값임
- `axis=None`: 전체 값을 하나로 펼쳐 계산함
- `axis=0`: 행 방향으로 내려가며 계산함, 열별 결과가 남음
- `axis=1`: 열 방향으로 이동하며 계산함, 행별 결과가 남음
- 핵심: axis는 계산 후 사라지는 축임


In [9]:
arr = np.arange(1, 7).reshape(2, 3)  #[[1,2,3],[4,5,6]]
print(arr)

# 최소값 구하기
print("arr.min(axsis=None)", arr.min(axis=None)) # 전체 최소값

#axsis=0: 행 방향으로 내려가면서 같은 열의 초솟값 구하기
print("arr.min(axsis=None)", arr.min(axis=0))

#axsis=1: 열 방향으로 내려가면서 같은 열의 초솟값 구하기
print("arr.min(axsis=None)", arr.min(axis=1))


[[1 2 3]
 [4 5 6]]
arr.min(axsis=None) 1
arr.min(axsis=None) [1 2 3]
arr.min(axsis=None) [1 4]


In [11]:
# 합걔
print("arr.sum()", arr.sum()) # axis미작성 == 기본값 (axis=None)
# 행의 합계
print("arr.sum(axsis=0)", arr.sum(axis=0))
# 열의 합계
print("arr.sum(axsis=1)", arr.sum(axis=1))

arr.sum() 21
arr.sum(axsis=0) [5 7 9]
arr.sum(axsis=1) [ 6 15]


In [13]:
# 평균 arr.mean() : 수학적 평균
print("arr.mean()", arr.mean())
print("arr.mean(axis=0)", arr.mean(axis=0))
print("arr.mean(axis=1)", arr.mean(axis=1))


arr.mean() 3.5
arr.mean(axis=0) [2.5 3.5 4.5]
arr.mean(axis=1) [2. 5.]
