# 정렬
- 배열 값을 기준에 따라 순서대로 배치하는 작업임
- 오름차순/내림차순 정렬 가능함
- 원본 유지 여부 확인 필요함


In [3]:
import numpy as np

In [2]:
# np.sort(ndarray)
# - 정렬된 새 배열을 반환
# - 원본 배열 유지
# - 원본데이터 유지 여부는 데이터 전처리에 있어 중요한 부분이다

arr = np.random.randint(1, 11, 10)
print("arr : ", arr)

print("np.sort(arr) : ", np.sort(arr))
print("arr : ", arr, "\n")

arr :  [4 5 5 7 6 7 6 5 9 2]
np.sort(arr) :  [2 4 5 5 5 6 6 7 7 9]
arr :  [4 5 5 7 6 7 6 5 9 2] 



In [3]:
# 내림차순(역순정렬) -> 슬라이싱 방식 이용
np.sort(arr)[::-1]

array([9, 7, 7, 6, 6, 5, 5, 5, 4, 2])

In [8]:
# 2차원 배열 형태의 정렬
# axis에 따라 정렬 기준이 달라짐
# - axis : None - 전체 ( 1차원으로 변경 후 정렬)
# - axis : 0    - 각 행 안에서 열 방향으로 정렬
# - axis : 1    - 각 열 안에서 행 방향으로 정렬
np.random.seed(1)
arr2d = np.random.randint(1, 15, (3, 4))
print("arr2d : \n", arr2d)

print("axis:None:\n", np.sort(arr2d, axis=None))  # 1차원 변경 후 정렬
print("axis:0:\n", np.sort(arr2d, axis=0))  # 행 정렬
print("axis:1:\n", np.sort(arr2d, axis=1))  # 열 정렬


arr2d : 
 [[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]
axis:None:
 [ 1  1  2  6  6  8  9 10 12 12 13 13]
axis:0:
 [[ 1  2  6  1]
 [ 6 12 13  8]
 [10 12 13  9]]
axis:1:
 [[ 6  9 12 13]
 [ 1  6 10 12]
 [ 1  2  8 13]]


## np.argsort()
- 배열 요소를 정렬했을 때의 인덱스를 반환함
- 정렬된 값 자체가 아니라 정렬 순서임
- 실제 정렬값은 `arr[indices]`처럼 다시 인덱싱해야 함


In [15]:
# 값의 순서를 정렬해서 정렬된 인덱스 값을 보여줌
arr = np.array([40, 10, 20, 30])
indices = np.argsort(arr)

indices = np.argsort(arr)
print("indices : ", indices)
print("arr[indices] : ", arr[indices])

print("")

# 역순정렬은 "-" 붙여서 정렬
revers = np.argsort(-arr)
print("revers : ", revers)
print("arr[revers] : ", arr[revers])



indices :  [1 2 3 0]
arr[indices] :  [10 20 30 40]

revers :  [0 3 2 1]
arr[revers] :  [40 30 20 10]


In [18]:
# 2차원 argsort(axsis = 0)
arr = np.array(
    [
        [30, 10, 20],
        [60, 40, 50]
    ])

indices = np.argsort(arr, axis=0)
print("indices axis = 0")
print(indices)
print(arr[indices])



indices axis = 0
[[0 0 0]
 [1 1 1]]
[[[30 10 20]
  [30 10 20]
  [30 10 20]]

 [[60 40 50]
  [60 40 50]
  [60 40 50]]]


In [4]:
# 각 배열의 같은 인덱스 요소가 한 학생의 이름, 점수를 나타냄
# 학생의 이름을 점수 내림차순 순서로 정렬
names = np.array(['홍길동', '신사임당', '이순신', '유관순'])
scores = np.array([90, 30, 50, 70])

['홍길동','유관순','신사임담','유관순']

a = np.argsort(-scores)
print(a)
print(f"이름:{names[a]}")
print(f"점수 : {scores[a]}")

aa = np.sort(scores, axis=0)
print(aa)



[0 3 2 1]
이름:['홍길동' '유관순' '이순신' '신사임당']
점수 : [90 70 50 30]
[30 50 70 90]


In [6]:
# 우선순위에 따른 작업 정렬(작은 수일수록 높은 우선 순위)
priorities = np.array([3, 1, 2, 5, 4])
tasks = np.array(["Task A", "Task B", "Task C", "Task D", "Task E"])

# 결과: ["Task B" "Task C" "Task A" "Task E" "Task D"]

b = np.argsort(priorities)
print("tasks : ", tasks[b])

tasks :  ['Task B' 'Task C' 'Task A' 'Task E' 'Task D']
