# ndarray 형태변경
- `reshape()`: 원소 개수는 유지하고 배열 모양만 변경함
- `resize()`: 배열 크기 변경함, 원본 수정 가능함
- `ravel()`: 다차원 배열을 1차원으로 펼침
- `expand_dims()`: 지정 axis에 새 차원 추가함
- `squeeze()`: 크기가 1인 차원 제거함
- `transpose()`: 배열 축을 전치함
- `swapaxes()`: 두 축을 서로 교환함
- `rollaxis()`: 지정 축 위치를 이동함
- `moveaxis()`: 축 순서를 변경함
- `broadcast_to()`: 배열을 지정 shape로 broadcast함
- `broadcast_arrays()`: 여러 배열을 broadcast 가능한 형태로 맞춤
- `concatenate()`: 배열 연결함
- `stack()`: 새 축을 만들며 배열을 쌓음
- `hstack()`: 가로 방향으로 배열을 쌓음
- `vstack()`: 세로 방향으로 배열을 쌓음
- `dstack()`: 깊이 방향으로 배열을 쌓음
- `split()`: 배열을 나눔
- `hsplit()`: 가로 방향으로 배열을 나눔
- `vsplit()`: 세로 방향으로 배열을 나눔
- `dsplit()`: 깊이 방향으로 배열을 나눔
- `tile()`: 배열을 반복 배치함
- `repeat()`: 배열 원소를 반복함
- `unique()`: 중복 제거 후 고유값 반환함
- `flip()`: 배열 원소 순서를 뒤집음
- `fliplr()`: 좌우 방향으로 뒤집음
- `flipud()`: 상하 방향으로 뒤집음
- `roll()`: 배열 원소를 순환 이동함
- `rot90()`: 배열을 90도 회전함


In [ ]:
import numpy as np

In [ ]:
# reshpe() : 지정된 배열의 모양(차원) 변경
# -1 : 남은 차원의 수를 numPOy에게 자동 계산하라고 지시
arr = np.arange(12)

# arr.reshape(3,4)
# -1을 풀면
# 3팽으로 만들고 열의 개수는 알아서 해라(자동계산)
arr.reshape(3, -1)
#  행의 개수는 전체 사이즈의 약수만 가능함
# arr.reshape(5,-1)

# 열은 4개 행은 자동계산
arr.reshape(-1, 4)

# 기준이 없으므로 안됨
# arr.reshape(-1, -1)

In [ ]:
# ravel : 다차원 배열일 1차원 배열로 변환
# [중요]: revel()의 결과 1차원 배열은 원본과 값을 공유한다
arr = np.arange(12).reshape(3, 4)

flat = arr.ravel()


In [ ]:
# revel() 결과의 값을 수정
flat[0] = 100
print(arr)
print(flat)

In [ ]:
# 깊은복사본이 필요하면 flatten()을 사용 함
flat2 = arr.flatten()
flat2[0] = 200
print(arr)
print(flat2)

In [ ]:
# expend_dims(ndarray, axis) : 지정한 축에 차원 추가
arr = np.arange(1, 11)
print("arr.shape", arr.shape)
print("arr", arr)

arr2 = np.expand_dims(arr, axis=0)
print("arr2 axis 0 추가")
print(arr2)

arr3 = np.expand_dims(arr, axis=1)
print("arr3 axis 1 추가")
print(arr3)

arr4 = np.expand_dims(arr2, axis=1)
print(arr4, arr4.shape)


In [ ]:
# squeeze(ndarray, axis) : 지정된 차원 (축) 제거
# 단, 길이가 1인 축만 제거 가능
# 차원이 1인 부분만 긁어낸다 : 없앤다

arr = np.array([[1, 2, 3]])  # shape(1,3) 2차원 요소1, 1차원 요소 3
print(arr, arr.shape)

arr2 = np.squeeze(arr, axis=0)
print(arr2, arr2.shape)

In [ ]:
arr3 = np.array([[1], [2], [3]])  # 3,1
print("arr3.shape : ", arr3.shape)
print("arr3 : ")
print(arr3)

arr4 = np.squeeze(arr3, axis=1)
print("arr4.shape : ", arr4.shape)
print("arr4")
print(arr4)

In [ ]:
# 3차원 배열
arr = np.array([[[1, 2, 3]]])
print("arr.shape, arr:", arr.shape, arr)

# arr2 = np.squeeze(arr, axis=0)
# print("arr2.shape, arr2:", arr2.shape, arr2)

In [33]:
# 정사각형 행렬
# transspose(ndarray) : 전치 연산
# 행과 열을 바꾸는 연산
# 행렬곱 연산시 많이 사용
# - 전치연산은 행렬 곱을 맞추거나, 데이터 축 방향르 바꿀때 자주 사용함

arr = np.arange(1, 10).reshape(3, 3)
print("arr : ")
print(arr)

np.transpose(arr)
print("transpose : ")
print(np.transpose(arr))

print("arr.transpose() : ")
print(arr.transpose())
print("arr.T : ")
print(arr.T)

arr : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
arr.transpose() : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
arr.T : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [32]:
# 직사각형 행렬
arr = np.arange(1, 7).reshape(2, 3)
print("arr : ")
print(arr)

np.transpose(arr)
print("transpose : ")
print(np.transpose(arr))

print("arr.transpose() : ")
print(arr.transpose())
print("arr.T : ")
print(arr.T)

arr : 
[[1 2 3]
 [4 5 6]]
transpose : 
[[1 4]
 [2 5]
 [3 6]]
arr.transpose() : 
[[1 4]
 [2 5]
 [3 6]]
arr.T : 
[[1 4]
 [2 5]
 [3 6]]


In [43]:
# 행렬곱 ( 내적연산, dot product)에서 전치 연산 사용
# - 형렬곱 조건 : 왼쪽 행렬의 열의 수 == 오른쪽 행렬의 행의 수
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(1, 7).reshape(2, 3)

print("arr1 : ")
print(arr1)

print("arr2 : ")
print(arr2)

# print("arr1 @ arr2 :")
# print(arr1 @ arr2)

print("arr1 @ arr2.T :")
print(arr1 @ arr2.T)

print("arr1.T @ arr2 :")
print(arr1.T @ arr2)

arr1 : 
[[1 2 3]
 [4 5 6]]
arr2 : 
[[1 2 3]
 [4 5 6]]
arr1 @ arr2.T :
[[14 32]
 [32 77]]
arr1.T @ arr2 :
[[17 22 27]
 [22 29 36]
 [27 36 45]]
