# [4] Numpy: 통계

### [실습 1] 중심 경향 및 산포 측도 계산


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.


```python
	arr = np.array([10, 20, 30, 30, 40, 50, 60])
```

In [1]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 30, 40, 50, 60])

print("평균 : ", np.mean(arr) )
print("중앙값 : ", np.median(arr))

# 중복값 제거 후
values, counts = np.unique(arr, return_counts=True)
max_count = np.max(counts)
# 중복제거 이후 최빈값을 가진 수만 추출
print("최빈값:", values[counts == max_count])
print("분산:",np.var(arr))
print("표준편차:",np.std(arr))
print("범위:",np.ptp(arr))



평균 :  34.285714285714285
중앙값 :  30.0
최빈값: [30]
분산: 253.06122448979593
표준편차: 15.90789817951435
범위: 50


### [실습 2] 정규분포와 균등분포의 난수 생성


정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [6]:
arr = np.random.normal(0, 1, 1000)
# print(arr)
arr2 = np.random.rand(1000)
print(arr2)

[0.10743532 0.13059199 0.12309199 0.20294864 0.66247928 0.09365328
 0.23616758 0.67296864 0.05037204 0.13768965 0.61179091 0.8925517
 0.39095043 0.74526857 0.65103916 0.44505776 0.87706198 0.27534619
 0.48063498 0.15282094 0.85655491 0.19555532 0.04303088 0.63615141
 0.16962449 0.02836721 0.92417384 0.70477801 0.55705839 0.87239584
 0.66428702 0.08003228 0.22588941 0.15531874 0.18480947 0.42490997
 0.81918412 0.47810222 0.91943044 0.96420814 0.40011603 0.23064438
 0.9401526  0.24177568 0.93045944 0.84722762 0.39082453 0.8199887
 0.43466528 0.6929453  0.54771539 0.23454302 0.72289379 0.05863572
 0.27229255 0.7277386  0.89048592 0.72573453 0.08469586 0.5264325
 0.55552684 0.73573232 0.09022872 0.03831268 0.88268523 0.54450795
 0.04135049 0.51589156 0.68083296 0.78878124 0.03475839 0.75308552
 0.65869233 0.66070502 0.5257713  0.65232925 0.65547885 0.30152823
 0.53751925 0.32169428 0.84215068 0.7594894  0.90617072 0.84076613
 0.16698928 0.80180315 0.48487112 0.44704461 0.86288306 0.4782653

### [실습 3] 평균 성적 구하기


아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.


```python
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]
```

In [21]:
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

arr_math = np.array(scores_math)
print(arr_math)
arr_eng = np.array(scores_english)
print(arr_eng)
arr_sen = np.array(scores_science)
print(arr_sen)
# np.mean(arr_math, arr_eng, arr_sen)

means = np.mean([arr_math, arr_eng, arr_sen])

arrs = np.array([arr_math, arr_eng, arr_sen])
print("전체평균", means)
print("분산", np.var(arrs))
print("분산", np.std(arrs))


# print("수학 평균 : ")

[88 92 76 85 95 92 88 90 85 88]
[90 85 80 87 92 89 83 91 86 88]
[85 88 82 89 94 86 91 88 84 87]
전체평균 87.46666666666667
분산 16.115555555555552
분산 4.014418457953226
